### ISSUE TITLE
GtkWarning

### ISSUE THREAD

**Issue by cpbridges** [daniestevez/gr-kiss#1]
Hi Dani,

Just trying your code with some new recordings and have the following error:

```
******* MESSAGE DEBUG PRINT ********
(() . #[� 7 ^  G [ � D �])
************************************
/usr/local/lib/python2.7/dist-packages/gnuradio/grc/gui/Dialogs.py:65: GtkWarning: gtk_text_buffer_emit_insert: assertion 'g_utf8_validate (text, len, NULL)' failed
  self.get_buffer().insert(self.get_buffer().get_end_iter(), line)
```

I'm on Ubuntu 16.04 LTS laptop.

Also, is there a hex mode rather than viewing ASCII?

73s Chris

**Comment by daniestevez** [comment]
Hi Chris,

You can use the "print_pdu" input instead of the "print" input in the "Message Debug" block to print PDUs in hex. Are you using one of the flowgraphs in the `examples` folder or your own flowgraph? All the flowgraphs in the `examples` folder use "print_pdu", so they shouldn't give that error.

**Comment by cpbridges** [comment]
Ah, yes. Silly me!
